### ISSUE TITLE
Profile Creation Confirmation Page

### ISSUE THREAD

**Issue by erin2722** [spectatorpublishing/Clubs-2020#100]
## Component Description and Screenshot
**Description:**
A page containing static component for when the user has finished making their club.

**Screenshot:**
<img width="226" alt="Screen Shot 2020-12-03 at 9 33 25 PM" src="https://user-images.githubusercontent.com/16248113/101114381-5a920500-35af-11eb-9b0a-3de2cb543714.png">

![Profile Creation Confirmation](https://user-images.githubusercontent.com/61126997/104766283-51f92680-5738-11eb-8785-ec7a613f3e1e.png)

![Confirmation Page](https://user-images.githubusercontent.com/61126997/104766307-57ef0780-5738-11eb-8ebb-2328ff552e6f.png)

## Styling Notes
see figma: https://www.figma.com/file/XRecRGPXEPBbuhgt6OlA6I/Final-(prototyped)-%2B-design-specs?node-id=1156%3A301

## Additional Notes
Use a font awesome icon for the email icon! See examples of how to do this in socialTagsBox
https://fontawesome.com/icons/envelope?style=regular

**Comment by lauracastrovenegas** [comment]
- Looks like the component has been made by admin team --> https://github.com/spectatorpublishing/Clubs-2020/pull/68
- Unsure if Confirmation Page has been put together.
- Pending updates from admin team
