### ISSUE TITLE
Manage username/password component

### ISSUE THREAD

**Issue by erin2722** [spectatorpublishing/Clubs-2020#101]
## Component Description and Screenshot
**Description:**
for when user opts to change their password

**Screenshot:**
<img width="506" alt="Screen Shot 2020-12-03 at 9 43 37 PM" src="https://user-images.githubusercontent.com/16248113/101115119-d3459100-35b0-11eb-9ba3-196034768619.png">
(ignore the pink text)

## Props and State
**Props:** the username and password
**State:**

## Styling Notes
see mockup: https://www.figma.com/file/XRecRGPXEPBbuhgt6OlA6I/Final-(prototyped)-%2B-design-specs?node-id=1048%3A1032

**Comment by lauracastrovenegas** [comment]
Component made my admin team #65, PR has been closed and branch made has been deleted.
