### ISSUE TITLE
Backend setup research - Tanner

### ISSUE THREAD

**Issue by wangyyt1013** [spectatorpublishing/Clubs-2020#43]
**Action item**
Compile research doc with findings regarding: 
- Hosting services
  - Specific services to recommend for IaaS
  - Specific services to recommend for PaaS
  - **NOTE: comparison based on 1) performance 2) pricing 3) hassle/manpower
- Database
  - Sql vs. nosql comparisons (pros and cons)
  - For sql, which db and which hosting option?
  - For nosql, which db and which hosting option?
  - **NOTE: comparisons based on 1) how fully it supports our app functionalities; 2) how easy it is to implement 3) how robust it is 4) hosting pricing
  - **NOTE2: we’d be dealing with a small amount of static data (potentially < 100MB)

**Deliverables**
Research doc compiling the findings
1. Attach links/references if necessary
2. Organize doc based on the topic structure above
3. Clearly indicate the prices of your recommendations

**Proposed solution**
Description of specific steps you'll take / changes you'll introduce.

**Alternatives/WIPs**

**Comment by TannerTreasure** [comment]
https://docs.google.com/document/d/1OVGBrLrWCIA4p8TDmU2oNyh18Ac_MceUD5DnUktDVgk/edit?usp=sharing
